"""Edition sınırını koruyan, paket içi MangaX sürüm notları."""
from __future__ import annotations
from typing import Any
RELEASE_NOTES: dict[str, dict[str, Any]] = {'v0.13.2': {'common': ['MyAnimeList hesabı bağlı görünmesine rağmen bazı listelerin kütüphaneye hiç aktarılmamasına neden olan Full eşleştirme kaybı düzeltildi.', 'AniList eşleşmesi bulunamayan MAL kayıtları artık güvenli mal_<id> kimliğiyle korunuyor; ağ ve istek sınırı hataları başarısız aşamayı açıkça gösteriyor.']}, 'v0.13.1': {'common': ['MyAnimeList hesap bağlantısında uzun OAuth doğrulama kodlarının reddedilmesine neden olan callback sınırı düzeltildi.', 'Geçerli uzun bağlantı kodları kabul edilirken aşırı büyük istekler güvenli üst sınırla reddedilmeye devam ediyor.']}, 'v0.13.0': {'common': ['MyAnimeList hesabı artık Reader ve Full sürümlerinde hazır uygulama kimliğiyle doğrudan bağlanabiliyor.', 'MAL listesinin otomatik ve isteğe bağlı çift yönlü senkronizasyonu güvenli tarayıcı bağlantısı ve Windows kimlik kasasıyla birlikte sunuluyor.']}, 'v0.12.11': {'common': ['MyAnimeList bağlantısı artık Reader ve Full sürümlerinde hazır uygulama kimliğiyle doğrudan başlatılabiliyor.', 'Bağlantı tarayıcıdaki güvenli OAuth ekranında tamamlanıyor; Client Secret ve hesap tokenları uygulama paketine eklenmiyor.']}, 'v0.12.10': {'common': ['İsteğe bağlı çift yönlü MyAnimeList eşitlemesiyle durum, puan ve okuma ilerlemesi MAL hesabına güvenli biçimde gönderilebiliyor.', 'Bekleyen değişiklikler kalıcı kuyrukta tutuluyor; iki tarafta aynı kayıt değiştiğinde hangi sürümün korunacağı kullanıcıya soruluyor.']}, 'v0.12.9': {'common': ['MyAnimeList otomatik eşitlemesi artık açılışta, 6, 12 veya 24 saatlik aralıklarla çalışacak şekilde ayarlanabiliyor.', 'Yakın zamanda eşitlenen listeler gereksiz yere yeniden istenmiyor; çevrimdışı hatalar açılışı etkilemeden sınırlı biçimde yeniden deneniyor.']}, 'v0.12.8': {'common': ['MyAnimeList entegrasyon ekranı bağlı hesap, son eşitleme, toplam manga ve otomatik eşitleme durumunu tek yerde gösteriyor.', 'Canlı eşitleme ilerlemesi ayrıntılandırıldı; MAL kayıtları kütüphanede sade bir rozetle ayırt edilebiliyor.']}, 'v0.12.7': {'common': ['MyAnimeList hesabı bağlandığında ilk kütüphane eşitlemesi artık otomatik olarak arka planda başlıyor.', 'Entegrasyonlar ekranına canlı aşama, ilerleme, sonuç sayaçları ve güvenli iptal denetimleri eklendi.']}, 'v0.12.6': {'common': ['MyAnimeList manga listesinin tamamını kopya oluşturmadan eşitleyen yeni senkronizasyon altyapısı eklendi.', 'MAL durumu, puanı ve okunan bölüm/cilt bilgileri güncellenirken yerel notlar, koleksiyonlar ve dosyalar korunuyor.']}, 'v0.12.5': {'common': ['MyAnimeList’teki Okuma Planı kayıtları artık kütüphanede ayrı bir durum olarak gösteriliyor.', 'Kütüphane durum filtrelerine anlık seri sayaçları eklendi.']}, 'v0.12.4': {'common': ['Başlangıç sihirbazı artık yalnızca ilk kurulumda gösteriliyor.', 'Güncellemeden sonra yeni özellikleri bir kez gösteren sürüm özeti eklendi.'], 'reader': ['MyAnimeList hesabı ve manga listesi Entegrasyonlar bölümünden yönetilebiliyor.']}}

def release_notes_for(version: str, edition: str) -> dict[str, Any] | None:
    entry = RELEASE_NOTES.get(str(version or '').strip())
    normalized_edition = str(edition or '').strip().lower()
    if not isinstance(entry, dict) or normalized_edition not in {'reader', 'full'}:
        return None
    common = [str(item) for item in entry.get('common', []) if str(item).strip()]
    edition_items = [str(item) for item in entry.get(normalized_edition, []) if str(item).strip()]
    if normalized_edition == 'full':
        raise RuntimeError('Reader çevrimiçi servis içermez.')
        edition_items.extend(full_release_notes_for(version))
    items = [*common, *edition_items]
    if not items:
        return None
    return {'version': version, 'edition': normalized_edition, 'items': items}
